# Generated by Django 4.1.7 on 2023-03-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='release_date',
            field=models.DateField(default='2001-01-01'),
            preserve_default=False,
        ),
    ]
